import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Products-GadgetsBD',
  description: 'Generated by Next.js',
}

export default function ProductLayout({ children }) {
  return (
    
      <div>
        <Navbar />
        {children}
        <Footer />
      </div>
    
  )
}
